version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: product
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  product:
    container_name: product_microservice
    build: .
    volumes:
      - ./config.yml:/app/config.yml:ro
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres: