version: '3.5'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db     
  product:
    container_name: product_microservice
    build: .
    volumes:
      - ./config.yml:/app/config.yml:ro
    ports:
      - "8081:8081"
    restart: unless-stopped

volumes:
  postgres:
  mongo: